name: DVC ML Pipeline

on:
  push:
    branches: [ master, main ]

jobs:
  run-dvc-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

    - name: Reproduce pipeline
      run: dvc repro

    - name: Show metrics diff
      run: dvc metrics diff

    - name: Commit metrics (optional)
      run: |
        git config --global user.email "nguyenvannam2004.hd@gmail.com"
        git config --global user.name "nguyenvannam2004"
        git add metrics.json dvc.lock
        git commit -m "Update metrics" || echo "No changes"
        git push || echo "No changes to push"
