name: Run DVC Pipeline

on:
  push:
    branches:
      - master  # hoặc branch bạn đang làm việc

jobs:
  dvc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc dvc[gs] scikit-learn pandas matplotlib

    - name: Pull data from DVC remote (nếu có)
      run: |
        dvc pull || true

    - name: Reproduce pipeline
      run: |
        dvc repro

    - name: Show metric diff
      run: |
        dvc metrics diff
