name: Run DVC Pipeline

on:
  push:
    branches:
      - master

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc dvc[gs] scikit-learn

      - name: Run DVC pipeline
        run: dvc repro

      - name: Show metric diff
        run: dvc metrics diff
